### ISSUE TITLE
Unresponsive interface

### ISSUE THREAD

**Issue by ghost** [Z3r0byte/Magis#18]
As of version 0.6.0 the app becomes completely unresponsive and ends up crashing the device. 
It looks like a severe memory leak 
- HTC One M8
- Android 6.0

**Comment by Z3r0byte** [comment]
Could you give a bit more details? 

I would like to know when it's happening and what do you mean with 'unresponsive'? Could you please provide any screenshots?

Thank you in advance.

**Comment by ghost** [comment]
So when navigating through the interface the app gets slower and slower until it no longer responds to user input. 
Here's what I mean:
https://mrjasper.stackstorage.com/index.php/s/8wciAE1z9kOvk78

**Comment by Z3r0byte** [comment]
I see... However, on my phone it works totally fine. I really don't know what the problem could be... ☹. I'll look into the code and maybe I find something, but I don't think so. 

Do you know how logcat works? If so, could you please check the logs for something weird? Thanks in advance.

**Comment by ghost** [comment]
Sure,  I'll see if I can find anything. 
I'll keep you posted

**Comment by Z3r0byte** [comment]
Thanks!

**Comment by ghost** [comment]
Ok, so I just found something that might be interesting. Check out the logs [here](https://gist.github.com/JasperWeiss/be39ba461fd6112d9f45c7a04087f044)

Notice the part where it says 
`Choreographer: Skipped 67 frames!  The application may be doing too much work on its main thread`

Might be caused by this:

```

07-05 17:45:36.589  2837  3850 D PMS     : acquireHCC(32ace73): CPU_MIN_FREQ AbsListViewScroll_5.0 0x2000 24631 10182 null
07-05 17:45:36.591  2837  3660 D PMS     : acquireHCC(4132130): CPU_MIN_NUM AbsListViewScroll_5.0 0x8000 24631 10182 null
07-05 17:45:57.091  2837  3657 D PMS     : acquireHCC(b61f1a9): CPU_MIN_FREQ AbsListViewScroll_5.0 0x2000 24631 10182 null
07-05 17:45:57.096  2837  3855 D PMS     : acquireHCC(20b932e): CPU_MIN_NUM AbsListViewScroll_5.0 0x8000 24631 10182 null
```

Or this:

```

07-05 17:45:30.346 24631 24650 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb8b5d0a0
07-05 17:45:32.745 24631 24650 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb8d330c0
```

I'm not sure, programming is somewhat new to me :)

Edit:
Logcat indicates about 80-100% CPU usage by com.z3r0byte.magis
`
28295  1  80% S    26 1028108K  96736K  fg u0_a182  com.z3r0byte.magis`

Edit 2:
It seems to be missing some library for the ARM processor
`07-05 18:05:29.666 29753 29753 W System : ClassLoader referenced unknown path: /data/app/com.z3r0byte.magis-1/lib/arm`

**Comment by Z3r0byte** [comment]
Thanks for pointing some important things out.

However, I dont think 

> `Choreographer: Skipped 67 frames! The application may be doing too much work on its main thread`

is the issue, because, as seen in the video you sent, ripple effects are all working.

I think there might be something wrong with your installation because of this: 

> `07-05 18:05:29.666 29753 29753 W System : ClassLoader referenced unknown path: /data/app/com.z3r0byte.magis-1/lib/arm`

Have you tried reinstalling the app yet? If not, could you try that?

**Comment by ghost** [comment]
Yup, tried that. Twice actually. If the app somehow got corrupted it wouldn't pass the signature check anyway.

**Comment by Z3r0byte** [comment]
Hmm... Weird, and it wasn't there in 0.5.0?
And what's your processor? x86/x64

**Comment by ghost** [comment]
Interesting,  I've never heard of a x86/x64 smartphone. My One M8 uses a snapdragon 801 ARM processor (32 bit)

**Comment by ghost** [comment]
Interesting,  I've never heard of a x86/x64 smartphone. My One M8 uses a snapdragon 801 ARM processor (32 bit)

**Comment by Z3r0byte** [comment]
I may have found what caused the problem: from version 0.6.0 I'm using a updated gradle version. I'll downgrade it and build the next update with it.

**Comment by Z3r0byte** [comment]
I just uploaded the new update, could you please check if the bug is fixed?

**Comment by Z3r0byte** [comment]
I'm assuming it's fixed, if not reopen the issue.  😉
