### ISSUE TITLE
Bestandsnamen

### ISSUE THREAD

**Issue by wesselperik** [Z3r0byte/Magis#3]
De bestandsnamen zijn op dit moment niet goed geschreven. Ten eerste moet een class altijd beginnen met een hoofdletter (StartActivity ipv startActivity). Dit staat in [deze guidelines](https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md). Deze is dan wel niet officieel, maar houd mij vaak wel aan deze guidelines zodat de code fatsoenlijk leesbaar blijft.
Ten tweede, en dit is dan een beetje advies van mij, ik zou alles in het Engels doen. Classnamen, enz. Dit omdat het een opensourceproject is, en als er toevallig iemand van buitenaf wil helpen met een probleem, is het wel handig dat diegene ook een beetje weet wat alles betekend. :yum:

**Comment by Z3r0byte** [comment]
Goed punt ik zal het binnenkort veranderen. :wink: 

Gr.
Bas
